algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2022
// Seção de Declarações 
var
valor_peca:real
qtde_vendida:real
comissao:real
inicio
// Dados de Entrada
escreval("digite o valor da peça")
leia(valor_peca)
escreval("digite o quantidade vendida")
leia(qtde_vendida)
//processamento
comissao<-(valor_peca*qtde_vendida)*0.05
//Dados de Saída
escreval("A sua comissao é: ",comissao)
fimalgoritmo
