algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
qtdemin,qtdemax,quantidademedia: real
inicio
// Seção de Comandos 
escreval("digite o valor de quantidade mínima: ")
leia(QTDEMIN)
escreval("digite o valor da quantidade máxima: ")
leia(QTDEMAX)
//processamento
estoquemedio<-(QTDEMIN+QTDEMAX)/2
// Dados de Saída
escreval("O SEU ESTOQUE MEDIO É: ",estoquemedio)






fimalgoritmo
