algoritmo "exetimes_escolhacaso"

var
time:caracter

inicio
escreval("digite um time: ")
leia(time)

escolha time
        caso "sao paulo","santos","palmeiras","corinthians"
         escreval("eixo sao paulo")
        caso "flamengo","vasco","fluminese","botafogo"
         escreval("eixo rio de janeiro")
        outrocaso
         escreval("nao é nem do rj e nem de sp")

fimescolha

fimalgoritmo
