algoritmo "semnome"
// Função : Identificar se um num é positivo, negativo ou igual 0
// Autor :
// Data : 20/06/2022
// Seção de Declarações 
var
num : inteiro

inicio

escreval ("Digite um número: ")
leia(num)

se num < 0 entao
   //VERDADEIRO
   escreval("NEGATIVO")
   senao
   //FALSO
   se num > 0 entao
   //VERDADEIRO
   escreval("POSITIVO")
   senao
   //FALSO
   escreval("ZERO")
   fimse
   fimse






fimalgoritmo
